### ISSUE TITLE
CGA Problems with Motorola R2600 RF Analyzer

### ISSUE THREAD

**Issue by TB1632** [scrapcomputing/MCEBlaster#17]
Hi,
First thank you for this great work. Unfortunately i got some Problems with an RF Service Analyzer Model Motorola R2600B.
The Unit has an CGA Output, No more desribed about the Mode or the Video Chip. The Video Signal comes from an Asic, no more described  I got no full Picture, The Picture is Horizontal and Vertical cut off. I tried several Monitors, forced VGA Resolutions and all possible things. 

The Positive: The MCE Blaster works great with another RF Service Analyzer Model IFR 1600S . It has an EGA Output. The MCE Blaster does a really great Job ! So the Unit assembled by me works.

Aditionally i own an GBS 8219 Converter which accepts the CGA input from the Motorola. I also own an old (Amiga) Monitor Philips CM8833 II (clone of 1084S) which accepts the CGA also.

I am no Video specialist and my knowledge is only minimum Basic.

So i took some Pictures. First 4 the Motorola problems

![Image](https://github.com/user-attachments/assets/e64bc599-5e6a-421d-bef1-6c6d7c226d9a)

![Image](https://github.com/user-attachments/assets/7e37295c-4510-44fb-b82f-7d4425c52046)

![Image](https://github.com/user-attachments/assets/f5408ac6-f5d8-4452-a13e-a3be71968f2d)

![Image](https://github.com/user-attachments/assets/7b7ee468-5943-4045-889a-f1fb69427412)

2 Pictures with the working GBS8219

![Image](https://github.com/user-attachments/assets/94f47acf-fd32-418d-9b2d-20d89b6ffb1a)

![Image](https://github.com/user-attachments/assets/c55a33bb-cafa-412b-8d89-cc7564c14e23)

And the working MCE Blaster with an EGA input from an IFR 1600

![Image](https://github.com/user-attachments/assets/2677bc4a-6060-4984-ae18-585404baaf7d)

![Image](https://github.com/user-attachments/assets/89a2f93c-0581-4696-86a9-73ef88c1ac4e)

I am happy for any help and improvisation.

**Comment by scrapcomputing** [comment]
It's missing like 20% of the vertical screen. So it could be a non-standard CGA mode with more vertical lines. The MCE Blaster prints the detected mode, is it CGA 320x200 ?

**Comment by TB1632** [comment]
No, it detects 640 x200 CGA at 60 Hz , but, have a closer look there is missing about 20% of the Bottom and 20% of the right corner. Pressing Auto Adjust does no changes.

![Image](https://github.com/user-attachments/assets/ab5ad424-ff63-41d0-abd6-f7ac9548216d)

![Image](https://github.com/user-attachments/assets/748ecd3a-5979-4f41-8285-6c1aab144343)

**Comment by TB1632** [comment]
hi, its positive. pin 8 + 15,7 khz pin 9 60 hz positive

**Comment by scrapcomputing** [comment]
Thanks! Could you try the attached firmware? I changed the CGA resolution to 640x350, similar to EGA. Let's see if it works :)

**Comment by TB1632** [comment]
I cant find any other firmware, sorry...

**Comment by hitchhiker85** [comment]
same problem in my thread.. i think need a special formware :( thanks

**Comment by scrapcomputing** [comment]
@TB1632 Oops sorry about that. The attachment had failed to upload for some reason. I fixed it in my original comment.

**Comment by TB1632** [comment]
Hi, i tried the modified Firmware but nothing changes. Missing Bottom and right Corner. Blaster says CGA 640x200 at 60 Hz. 14,257 Mhz Pixl Clock. VGA Monitor says 720 x 400 V 70Hz H 31Khz. I have checked all Settings and Resolutions. No Changes.
Problem ist still the same.

If you are able and want spend some time for me, i will check other modified Firmwares which you provide.
Thank you..

![Image](https://github.com/user-attachments/assets/d3f92a4d-ab0d-406e-aadf-79acb1e4b9d1)

**Comment by scrapcomputing** [comment]
I think I forgot to disable line-doubling, this should make it fit vertically. As for the width I think increasing the pixel clock on the MCE blaster should make it fit horizontally. Please try the attached firmware in case it works this time.

Do you think you could measure the vertical resolution by measuring how many HSync pulses fit within two consecutive VSync pulses? This should help us with filling in the correct values.

[MCEBlaster_CGA_640x350_15.7KHz_16.267MHz.uf2.zip](https://github.com/user-attachments/files/19901340/MCEBlaster_CGA_640x350_15.7KHz_16.267MHz.uf2.zip)

**Comment by TB1632** [comment]
Hi.
I have testetd the new firmware. Blaster initiates with your logo and colorbar screen. If i put it to the cga conector vga signal goes off and i got a black screen. i tried several monitors all the same , No VGA signal..

**Comment by scrapcomputing** [comment]
Hmm please try this one.

[MCEBlaster_CGA_640x350_15.7KHz_16.267MHz.uf2.zip](https://github.com/user-attachments/files/19911515/MCEBlaster_CGA_640x350_15.7KHz_16.267MHz.uf2.zip)

**Comment by crasbe** [comment]
@TB1632 took some measurements with his oscilloscope and frequency counter of the HSYNC and VSYNC signals.
I'm writing on his behalf because he is currently busy with less-fun work.

These are the oscilloscope measurements:

![Image](https://github.com/user-attachments/assets/03459a3c-18e5-446b-97ed-7f9b765263bf)

![Image](https://github.com/user-attachments/assets/54e65964-e627-40a8-be06-6bfea906572a)

![Image](https://github.com/user-attachments/assets/09757632-b903-48d1-8ed6-e5d93008e115)

And this is from the frequency counter:

![Image](https://github.com/user-attachments/assets/7584b89b-06db-4362-ad69-2617c8809785)

![Image](https://github.com/user-attachments/assets/7ccdebb9-a86b-4ba3-a0b6-d1e5b8a6496d)

From the values it looks like the line count is 261 or 260 (depending on if you count the HSYNC pulse during the VSYNC):
15,723.269Hz / 60.2524Hz = 261.0000

<hr/>

Later this evening we want to try to measure the pixel width of of green frame or the blue grid, as they should be discernable on the oscilloscope.
With the pixel width, it should be possible to estimate the horizonal pixel count by dividing the time between two VSYNCs by the pixel width we measured.

**Comment by crasbe** [comment]
We tried to measure some individual pixel widths.

I assume that these are 6 pixels, around 560ns:
![Image](https://github.com/user-attachments/assets/cf598ddf-ab86-4486-83fb-235123999d8b)

And that this are 2 pixels, around 185ns:
![Image](https://github.com/user-attachments/assets/b094fac9-3bb7-4956-9b38-3c1f7a4acd55)

With the 15.723269kHz VSYNC, we have 63.60000µs per line.

That would give the following pixel counts:
63600ns / (185ns / 2) = 687.57px
63600ns / (560ns / 6) = 681.43px

Unfortunately this is somewhat at the end of the bandwidth of this oscilloscope, it's only a 20MHz scope.

I am not super sure though that those are actually 2 and 6 pixels. It would be possible that it's actually just 1 and 3 pixels, which would result in a resolution of 340x260px and they were just pushing the limits of what an external CGA monitor could reliably show 🤔 

<hr/>

This is the image with the latest firmware:

![Image](https://github.com/user-attachments/assets/f58824e2-6ec4-4d38-a95d-c72c6da774f8)

![Image](https://github.com/user-attachments/assets/70a98985-0b7e-4571-b63c-0323e699bf62)

**Comment by crasbe** [comment]
I just wanted to express how grateful we are that you are investing your time to find a solution here, this is really awesome :)

If the tube or transformer were to die in the RF analyzer, there would be no replacement available and external CGA monitors or converters are increasingly hard to come by.

**Comment by scrapcomputing** [comment]
Thanks for the measurements and for trying out the latest firmware.

260 HSync pulses is similar to standard CGA. This is usually 200 visible + 60 black. But I think in this case it is probably closer to 240 visible + 20 black. The only issue is that this needs to use VGA's 640x480 resolution, not the 640x400 one I am currently using.

**Comment by scrapcomputing** [comment]
Hi,

I have been working on a new firmware that should work better for your use case.
It is now stable enough for testing and it supports manually setting the TTL options:

- Press both buttons until the new menu shows up. The text [AUTO-TTL] should show up.
- Press the PxClk button once to change it to [MANUAL-TTL] and more options will show up including Mode, resolution and X and Y offsets.
- Cycle through the options by long-pressing either button, change values by short-pressing.
- The settings are saved to flash after 5 seconds or so.
- If you need to reset to defaults unplug the MCE Blaster from power and power it on again while pressing both buttons until you see the led blinking fast.

Please note that I have not done extended testing so feel free to report any bugs.

Thanks!

[MCEBlaster.rev.0.2.beta.uf2.zip](https://github.com/user-attachments/files/20432603/MCEBlaster.rev.0.2.beta.uf2.zip)

**Comment by scrapcomputing** [comment]
Just FYI: I just uploaded a new version of the firmware: https://github.com/scrapcomputing/MCEBlaster/releases/

**Comment by TB1632** [comment]
Hi.
I have testet the new Firmware. Now i am able in CGA Mode 640x240manual  to see the whole Picture, but only if i scroll manual the X and Y Axis.
It seems the CGA Resolution from Motorola is lager than 640x240, this is abolutly out of Norm. I could not choose higher Resolution in Blaster Menu in CGA and EGA Mode than 640x240. Also the VGA Mode does not switsch higher than 640x 480.

If it would be possible to go higer in resolution EGA CGA than 640, the VGA Mode will not be enough.

So i played arround with the MDA Mode(which is not usable in my case)  In MDA Mode its possible to go higher than 640x240 and the VGA Output switches to 800x600. So i was able to see the full Vertikal Screen , but changing Horizontal Resolution more than 240 the Blaster crashes and freezes. I have to do a Power Cycle and Change back to CGA or EGA.

Please dont waste Time for me for MDA Mode. Perhaps more Resolutionthan 640x240 in CGA Mode and automatic switching Output VGA to 800x600 can solve my Problem.
Thanks a lot for your Work

**Comment by scrapcomputing** [comment]
Ah nice, it already looks much better!

> I decreased the 240 resolution down about 100 , the "Ratio" Changes to 1/2 but the Picture is not shown full, 20 Lines are missing... so I turned back to 240.

I think you should increase the vertical pixels from 240 to 260, not decrease them. Because it seems that your input is 260 lines. At 240 you 20 lines won't show either from the top or from the bottom or both, depending on the Y offset. 
So please try 260 vertical by setting Manual TTL to: "MANUAL-TTL EGA 640 x 260 X: MANUAL 8 Y: MANUAL: 0".

**Comment by TB1632** [comment]
Yes this is a logic result to increase up to 260 but its not adjustable, Blaster settings stops  at 240.  I dont know if 20 lines are enough, perhaps it will be 22 or 23..  but as is said it ends at 240 max.

**Comment by scrapcomputing** [comment]
This must be a firmware bug, I will look into it and I will get back to you.

**Comment by TB1632** [comment]
Easy... easy, let me know how I can support you !!

**Comment by scrapcomputing** [comment]
For vertical resolutions 240-260 we would ideally switch to VGA 800x600 with line doubling but the Pico is not fast enough to support 800x600 for EGA/CGA. Disabling line-doubling at 241 would just sqeeze things vertically which won't look great. So let's try writing more than 480 visible lines vertically, perhaps the VGA monitors can tolerate it.

Please try the attached firmware, it might work.

As for the colors I am not sure why they would change, strange.

[MCEBlaster.VGA520.uf2.zip](https://github.com/user-attachments/files/20535368/MCEBlaster.VGA520.uf2.zip)

**Comment by TB1632** [comment]
OK we have reached the Goal !!
The CGA  Pic fits exactly in the VGA Monitor tolerance, i think it will not accetpt one Line more .
Please see the On Screen Text from Blaster in the VGA Monitor.

I have testet another Monitor ( Acer AL1716) fits exact the same, but have to play a little bit Pixl Clk with Blaster and Monitor. (normaly) The first Montor was an very old Gericom 15 inch. Native VGA max is 800x600, but is small and lightweight. Pefect for me in my Lab.

Increase Pxl Clk over 12 Mhz, correct Color comes back, i think this is a special issue by my Monitor. 

I NEED your PP to support.

![Image](https://github.com/user-attachments/assets/aaca7b95-5719-444a-901a-aaa207118564)

![Image](https://github.com/user-attachments/assets/ae8a73c3-7415-4131-93fc-379496b89e0a)

![Image](https://github.com/user-attachments/assets/7c0d7409-4a38-469b-b4a9-659a6b7c7ebb)

**Comment by scrapcomputing** [comment]
Awesome! Thanks for trying it out. I will push this as the latest firmware.

> I NEED your PP to support.

You've already helped so much by testing and reporting issues, thanks so much!

**Comment by TB1632** [comment]
YOU ARE WELCOME !!

**Comment by bg2wxo** [comment]
> I flashed the new 520 firmware, but it won't boot. I don't know why. What firmware did you flash?

**Comment by bg2wxo** [comment]
> 不客气 ！！



> 好了，我们达成目标了！ CGA图像正好符合VGA显示器的显示要求，我想它再也容不下更多行了。 请查看VGA显示器上Blaster的屏幕文字显示。
> 
> 我测试了另一台显示器（Acer AL1716），尺寸完全一样，但需要用 Blaster 和显示器稍微调整一下像素时钟。（正常情况下）第一台显示器是台很老的 Gericom 15 英寸显示器。它的 VGA 原生最大分辨率是 800x600，但它小巧轻便，非常适合我的实验室使用。
> 
> 将 Pxl Clk 频率提高到 12 MHz 以上，颜色就恢复正常了，我认为这是我的显示器特有的问题。
> 
> 我需要你的PP支持。
> 
> ![Image](https://github.com/user-attachments/assets/aaca7b95-5719-444a-901a-aaa207118564)
> 
> ![Image](https://github.com/user-attachments/assets/ae8a73c3-7415-4131-93fc-379496b89e0a)
> 
> ![Image](https://github.com/user-attachments/assets/7c0d7409-4a38-469b-b4a9-659a6b7c7ebb)I flashed the new 520 firmware, but it won't boot. I don't know why. What firmware did you flash?



> 您好，我尝试了修改后的固件，但问题依旧。屏幕底部和右下角没有图像。Blaster 显示 CGA 640x200 @ 60 Hz，像素时钟频率为 14,257 MHz。VGA 显示器显示 720 x 400 V 70Hz H 31Khz。我已经检查了所有设置和分辨率，但 问题仍然存在。 我尝试在显示器设置中滚动到屏幕底部和右下角，但仍然没有图像显示。它停在了照片中显示的位置。
> 
> 如果您有时间，并且愿意抽出一些时间，我会检查您提供的其他修改版固件。 谢谢。
> 
> ![Image](https://github.com/user-attachments/assets/d3f92a4d-ab0d-406e-aadf-79acb1e4b9d1)
I flashed the new 520 firmware, but it won't boot. I don't know why. What firmware did you flash?

**Comment by bg2wxo** [comment]
It is recommended to replace the internal CRT with an LCD. Comprehensive testing shows a longer lifespan. CRTs generate significant heat and consume around 30W of power, while LCDs use only about 5W, producing no heat. This reduces power load, lowers power supply temperature, and significantly decreases the overall internal temperature and weight of the machine
